# 使用官方 Python 镜像
FROM python:3.12
# 设置工作目录
WORKDIR /app

# 复制依赖文件
COPY requirements.txt .

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt

# 复制测试代码
COPY test_api.py .
COPY test_data.json .

# 设置容器启动时执行的命令
CMD ["python", "-m", "pytest", "test_api.py", "-v", "--alluredir=./allure-results"]